// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Cms.Admin.Sites;
using Dignite.Cms.Sites;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Cms.Admin.Sites;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISiteAdminAppService), typeof(SiteAdminClientProxy))]
public partial class SiteAdminClientProxy : ClientProxyBase<ISiteAdminAppService>, ISiteAdminAppService
{
    public virtual async Task<SiteDto> GetAsync()
    {
        return await RequestAsync<SiteDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(UpdateSiteInput input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateSiteInput), input }
        });
    }
}
