// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Cms.Public.Domains;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Cms.Public.Domains;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDomainPublicAppService), typeof(DomainPublicClientProxy))]
public partial class DomainPublicClientProxy : ClientProxyBase<IDomainPublicAppService>, IDomainPublicAppService
{
    public virtual async Task<DomainDto> FindByNameAsync(string domainName)
    {
        return await RequestAsync<DomainDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), domainName }
        });
    }
}
